# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Resolution', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JSONBrand', models.CharField(max_length=200)),
                ('JSONResolution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
                ('Tag', models.CharField(max_length=200)),
                ('Options', models.CharField(max_length=200)),
            ],
        ),
    ]
