# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camerarecommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionchar',
            old_name='Options',
            new_name='JSONOptions',
        ),
    ]
