# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camerarecommender', '0003_auto_20171031_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='Resolution',
            new_name='resolution',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='JSONBrand',
            new_name='json_brand',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='JSONResolution',
            new_name='json_resolution',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='SessionID',
            new_name='session_id',
        ),
        migrations.RenameField(
            model_name='questionchar',
            old_name='JSONOptions',
            new_name='json_options',
        ),
        migrations.RenameField(
            model_name='questionchar',
            old_name='Tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='questionchar',
            old_name='Text',
            new_name='text',
        ),
    ]
