# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camerarecommender', '0004_auto_20171031_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionChar',
            new_name='Question',
        ),
    ]
